version: 2
update_configs:
  - package_manager: "yarn"
    directory: "/"
    update_schedule:
      interval: "daily"
    updates:
      - package: "@loadmill/agent"
        update_type: "all"
        schedule:
          interval: "hourly"
