version: 2
jobs:
  build_macos:
    macos:
      xcode: "14.1.0"
    steps:
      - checkout
      - run:
          name: create-keychain
          command: sudo security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run:
          name: set-default-keychain
          command: sudo security default-keychain -s build.keychain
      - run:
          name: unlock-keychain
          command: sudo security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run:
          name: create CERT file
          command: echo $KEYSTORE | base64 --decode - > keystore.p12
      - run:
          name: codesign
          command: sudo security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign -T /usr/bin/productsign -A
      - run:
          name: install dependencies
          command: sudo yarn
      - run:
          name: package application
          command: sudo yarn package
      - run:
          name: create distribution files
          command: sudo yarn only-make
      - run:
          name: publish release
          command: sudo yarn forge-publish


workflows:
  version: 2
  build:
    jobs:
      - build_macos