name: Create a PR with updated @loadmill/agent and repo versions
on: push
  # schedule:
  #   # Check for updates every day at 12pm
  #   - cron: '0 12 * * *'

jobs:
  check-package-updates:
    runs-on: ubuntu-latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Check @loadmill/agent package updates
        run: yarn outdated @loadmill/agent
        id: outdated_agent_package
        continue-on-error: true
      - name: set failures
        if: steps.outdated_agent_package.outcome != 'success'
        run: echo "::set-output name=run_jobs::true"

  create-pr:
    needs: [check-package-updates]
    runs-on: ubuntu-latest
    if: needs.check-package-updates.run_rest_jobs == 'true'
    steps:
      - name: Get Latest @loadmill/agent Version
        run: echo "agent_latest_version=$(yarn info @loadmill/agent --json | python3 -c "import sys, json; print(json.load(sys.stdin)['data']['version'])")" >> $GITHUB_OUTPUT
        id: get_latest_agent_version
      - name: DISPLAY
        run: echo ${{ steps.get_latest_agent_version.outputs.agent_latest_version }}

      # - name: Create a PR with updated @loadmill/agent and repo versions
      #   if: steps.outdated_package.outputs.up_to_date != 'true'
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     # The title of the PR
      #     title: 'Update @loadmill/agent and repo versions'
      #     # The body of the PR
      #     body: 'This PR updates the @loadmill/agent package and repository versions to the latest versions.'
      #     # The branch where the changes will be made
      #     head: update-package-versions
      #     # The base branch to which the changes will be compared and merged
      #     base: master
